workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "AyuGram.xcodeproj"
        XCODE_SCHEME: "AyuGram"
      xcode: latest
    scripts:
      - name: Build iOS app (without code signing)
        script: |
          # Сборка только для симулятора (не требует подписи)
          xcodebuild -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build \
            clean build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_ENTITLEMENTS="" \
            DEVELOPMENT_TEAM=""
      - name: Find built app
        script: |
          find build -name "*.app" -type d
    artifacts:
      - build/**/*.app
